tak 1

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -9,6 +9,24 @@
 if [ $# -lt 4 ]
 then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+       exit
+fi
+
+# assigning parementals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabbling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$username@$ip:~/"
+
+#checking id the transfer was successful
+if [$? -eq 0]
+then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+	echo "FILE TRANSFER FAILED"
 fi
